# Generated by Django 4.1.7 on 2023-03-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_alumno', models.CharField(max_length=30)),
                ('apellido_alumno', models.CharField(max_length=80)),
                ('direccion_alumno', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=80)),
                ('duracion_curso', models.CharField(max_length=80)),
                ('Profesor_asignado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_profesor', models.CharField(max_length=30)),
                ('apellido_profesor', models.CharField(max_length=80)),
                ('direccion_profesor', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=120)),
            ],
        ),
    ]
